[project]
name = "jpx-derivatives"
version = "0.1.0"
description = "JPX Derivatives Data Management"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pyarrow>=19.0.0",
]
